### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'extend'

### ISSUE THREAD

**Issue by tlilly3** [jordanIAxelrod/MaterialsGenomeInitiative#4]
@jordanIAxelrod This line causes the AttributeError. What's the intended shape for `Uw`? It doesn't work if you replace with   `.reshape()`

https://github.com/jordanIAxelrod/MaterialsGenomeInitiative/blob/4698bb357e2cd9c554b806273d6a9ad366182608/src/neural_network.py#L62

**Comment by jordanIAxelrod** [comment]
Oh sorry about that. Reshape only moves around the entries that are there, extend duplicates tensors along dimensions. Let me take a look at a work around

**Comment by jordanIAxelrod** [comment]
Changed to repeat. for some reason they didnt implement extend but it does the same thing. Thanks for pointing this out
